esphome:
  name: "garagensteuerung"
  friendly_name: "Garagensteuerung"
  project:
    name: "vdwals.garagensteuerung"
    version: "1.2.0"
  name_add_mac_suffix: False
  area: "Garage"
  libraries:
    - emelianov/modbus-esp8266 # Required for communication with the modbus

# Enable logging
logger:
  baud_rate: 0
    
external_components:
    source: github://mapero/esphome-hcpbridge
    #source: github://vdwals/esphome-hcpbridge@feature/dual_connection
    refresh: 0s # Ensure you always get the latest version

packages:
  right_garage_door: !include
    file: hcpbridge.yml
    vars:
      rx_pin: 3
      tx_pin: 1
      lib: ""
      side: "rechts"
